This repository contains code for the useR2017 tutorial "Introduction
to optimal changepoint detection algorithms" by Toby Dylan Hocking and
Rebecca Killick.

Rebecca: Unsupervised changepoint detection, 90 minutes. TODO links.

Toby: [[http://members.cbio.mines-paristech.fr/~thocking/change-tutorial/Supervised.html][Supervised changepoint detection]], 90 minutes. source:
[[file:Supervised.Rmd]]. Options to follow along:
- Recommended: run the code on Rcloud
  https://rcloud.social/edit.html?notebook=699c9c7c6f47ce56358d6d9b8e548835
  (make sure to click the fork so you can makes changes).
- Rstudio: download
  https://raw.githubusercontent.com/tdhock/change-tutorial/master/Supervised.Rmd
  and open in Rstudio
  (maybe problems if you have old versions of R/packages).
- Look at the rendered Rmd
  http://members.cbio.mines-paristech.fr/~thocking/change-tutorial/Supervised.html
  and copy/paste into R on your computer.

** TODOs

For a more advanced tutorial, check out coarseDataTools::EMforCFR,
adapEnetClass, icenReg, and non-linear models.

Copy and adapt tutorial materials from [[https://github.com/eRum2016/Workshops/blob/master/details/An%2520introduction%2520to%2520changepoint%2520models%2520using%2520R.md][Rebecca's eRum2016 workshop]].

[[file:depmixS4.models.R]] tries to fit an HMM to the neuroblastoma data
set, but I ran into [[file:depmixS4.bugs.R]] -- I emailed the author
<i.visser@uva.nl> on May 31 but I haven't heard anything yet.

** 9 June 2017

Compare with BIC from PELT/fpop [[file:pelt.fpop.R]]

** 27 Apr 2017

[[http://members.cbio.mines-paristech.fr/~thocking/change-tutorial/Supervised.html][Compiled Rmd HTML Supervised changepoint tutorial]], first draft, source: [[file:Supervised.Rmd]].

** 28 Feb 2017

[[file:montreal-biohackathon-2017.org]] describes a changepoint detection
challenge for a 24 hour Biohackathon.

** 13 Feb 2017
[[file:figure-regression-interactive-some.R]] creates [[http://bl.ocks.org/tdhock/raw/eee5fd673c258ae554702d9c7c60f69b/][5 plot interactive data viz]].
** 9 Feb 2017

[[file:figure-regression-interactive-some.R]] for interactive figure with
a few profiles that we can zoom in
to. http://bl.ocks.org/tdhock/raw/9fc37a7aaf291cef364aab3fb41dd898/

[[file:figure-regression-interactive.R]] for comparing BIC and learned
model on entire neuroblastoma data set.

penaltyLearning package for exactModelSelection and targetInterval.

** 25 Nov 2016

Begin [[file:breakpoint.learning.cv.R]] which will read
[[file:breakpoint.learning.RData]] and estimate breakpoint predicted test
error via 6-fold cross-validation (including BIC, mBIC, supervised
penalty learning via iregnet).
