** TODOs

Compare with BIC from PELT [[file:pelt.models.R]]

CRAN submission because penaltyLearning has compiled code:
- remove test-peaks.R which needs coseg, PeakSegDP, and PeakError
  (remove from Suggests also)
- remove Remotes from DESCRIPTION.
- DONE: remove iregnet example.
- remove the following long examples, or put in if(interactive())
#+BEGIN_EXAMPLE
Examples with CPU or elapsed time > 5s
                                 user system  elapsed
IntervalRegressionCV          623.212  3.028 1256.107
modelSelectionR               106.232 70.304  180.940
IntervalRegressionRegularized  48.400  1.248   50.836
ROChange                       20.604  0.592   21.657
labelError                      9.204  0.460    9.754
largestContinuousMinimumC       6.540  0.496    7.356
targetIntervals                 6.488  0.468    7.198
largestContinuousMinimumR       6.204  0.440    6.803
modelSelectionC                 5.720  0.568    6.487
featureMatrix                   5.064  0.792    5.988
#+END_EXAMPLE
- DONE: fixed global variable issues by adding NULL variables.

For a more advanced tutorial, check out coarseDataTools::EMforCFR,
adapEnetClass, icenReg, and non-linear models.

Package for geom_tallrect / widerect?

Copy and adapt tutorial materials from [[https://github.com/eRum2016/Workshops/blob/master/details/An%2520introduction%2520to%2520changepoint%2520models%2520using%2520R.md][Rebecca's eRum2016 workshop]].

** 27 Apr 2017

[[http://members.cbio.mines-paristech.fr/~thocking/change-tutorial/Supervised.html][Compiled Rmd HTML Supervised changepoint tutorial]], first draft, source: [[file:Supervised.Rmd]].

** 28 Feb 2017

[[file:montreal-biohackathon-2017.org]] describes a changepoint detection
challenge for a 24 hour Biohackathon.

** 13 Feb 2017
[[file:figure-regression-interactive-some.R]] creates [[http://bl.ocks.org/tdhock/raw/eee5fd673c258ae554702d9c7c60f69b/][5 plot interactive data viz]].
** 9 Feb 2017

[[file:figure-regression-interactive-some.R]] for interactive figure with
a few profiles that we can zoom in
to. http://bl.ocks.org/tdhock/raw/9fc37a7aaf291cef364aab3fb41dd898/

[[file:figure-regression-interactive.R]] for comparing BIC and learned
model on entire neuroblastoma data set.

penaltyLearning package for exactModelSelection and targetInterval.

** 25 Nov 2016

Begin [[file:breakpoint.learning.cv.R]] which will read
[[file:breakpoint.learning.RData]] and estimate breakpoint predicted test
error via 6-fold cross-validation (including BIC, mBIC, supervised
penalty learning via iregnet).
