** TODOs

CRAN submission because penaltyLearning has compiled code:
- remove iregnet example.
- test-peaks.R which needs coseg, PeakSegDP, and PeakError.

Check out coarseDataTools::EMforCFR, adapEnetClass, icenReg, and
non-linear models.

Package for geom_tallrect / widerect?

Copy and adapt tutorial materials from [[https://github.com/eRum2016/Workshops/blob/master/details/An%2520introduction%2520to%2520changepoint%2520models%2520using%2520R.md][Rebecca's eRum2016 workshop]].

Scripts or Rmds for different steps in the supervised penalty learning
process.

** 28 Feb 2017

[[file:montreal-biohackathon-2017.org]] describes a changepoint detection
challenge for a 24 hour Biohackathon.

** 13 Feb 2017
[[file:figure-regression-interactive-some.R]] creates [[http://bl.ocks.org/tdhock/raw/eee5fd673c258ae554702d9c7c60f69b/][5 plot interactive data viz]].
** 9 Feb 2017

[[file:figure-regression-interactive-some.R]] for interactive figure with
a few profiles that we can zoom in
to. http://bl.ocks.org/tdhock/raw/9fc37a7aaf291cef364aab3fb41dd898/

[[file:figure-regression-interactive.R]] for comparing BIC and learned
model on entire neuroblastoma data set.

penaltyLearning package for exactModelSelection and targetInterval.

** 25 Nov 2016

Begin [[file:breakpoint.learning.cv.R]] which will read
[[file:breakpoint.learning.RData]] and estimate breakpoint predicted test
error via 6-fold cross-validation (including BIC, mBIC, supervised
penalty learning via iregnet).
